version: '3'
services:
  siege:
      image: centminmod/docker-centos6-siege
      links:
          - nginx
          - node1
          - node2
      tty: true
  nginx:
      image: nginx
      links:
          - node1:node1
          - node2:node2
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - "8080:80"
  node1:
      deploy:
          resources:
              limits:
                  cpus: '2'
                  memory: 50M
      build: .
      ports:
          - "8081:8080"
      command: pm2 start /usr/src/app/app.js
      command: bash
      tty: true
  node2:
      deploy:
          resources:
              limits:
                  cpus: '2'
                  memory: 50M
      build: .
      ports:
          - "8082:8080"
      command: pm2 start /usr/src/app/app.js
      command: bash
      tty: true